### PR TITLE
Concurrency tests

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Review by edwardsph — COMMENTED** [review]
These tests are not actually concurrent. An `await` in a for loop gives you a sequential set of operations.
* In the PUT test the first will succeed and the other 9 fail (there is no need to test more than 1 additional PUT).
* In the PATCH test, all 10 will succeed and the order will always be 0 to 9.

I would suggest you gather the fetches in an array and then do `await Promise.all()` - they will each start sequentially the moment you make the fetch call but will run concurrently while you await them all.

A trivial suggestion - you have exists3.ttl but since there are no other numbered files the `3` is a little random. To avoid any risk of overlapping filenames I would suggest using UUIDs as an easy alternative to manually trying to ensure each file is unique.

**Comment by michielbdejong** [comment]
Good point about the `Promise.all`! I had that previously but then moved it around and hadn't realised I broke it.

I would like to keep it as 10 requests instead of just 2, just to make (more) sure that timing overlap actually does occur on the server-side.

Changed the random 'example3.ttl' to 'resource.ttl'. The path already contains a timestamp, so no need to use a uuid as the resource name too.

Thanks!

**Comment by michielbdejong** [comment]
By the way,
* ESS is all-green on these tests now
* NSS is failing them, opened an issue about that: https://github.com/solid/node-solid-server/issues/1582
* CSS is failing these tests so far, due to known issue https://github.com/solid/community-server/issues/575

**Comment by edwardsph** [comment]
LGTM. I agree about 10 tests not 2 - just pointing out that you only need 2 when sequential.

**Comment by michielbdejong** [comment]
Thanks!!

**Pull request merged**
